# Generated by Django 4.2.2 on 2023-07-25 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_order_total_cost_order_paid_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='merchant_id',
            new_name='payment_intent',
        ),
    ]
